# Use the official Node.js 16 base image
FROM node:16

# Set the working directory inside the container
WORKDIR /

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install application dependencies
RUN npm install

# Copy the application code to the working directory
COPY . .

# # Expose the port your application listens on
# EXPOSE 3000

# Start the application
CMD [ "npm", "start" ]
