export const PRODUCT_SEARCH_QUERY = `query productSearchQuery($locale:Locale!,$text:String!){
    productProjectionSearch(locale:$locale,text:$text){
      results{
        id
        name(locale:$locale)
        masterVariant{
          sku
          id
          key
          images{
            url
            dimensions{
              height
              width
            }
          }
          price(currency:"USD"){
            id
            value{
              centAmount
              currencyCode
              fractionDigits
            }
          }
        }
        variants{
          sku
          id
          price(currency:"USD"){
            value{
              currencyCode
              centAmount
              fractionDigits
            }
          }
          images{
            url
          }
        }
        slug(locale:$locale)
      }
    }
  }`
export const FETCH_PRODUCT_LIST = `query productsList($limit: Int!, $offset: Int!, $sort: [String!]){
  products(limit:$limit,offset:$offset,sort:$sort){
    count
    total
    results{
      id
      version
      masterData{
        current{
          name(locale:"en-US")
          masterVariant{
            id
            sku
            key
            images{
              url
            }
            price(currency:"USD"){
              id
              value{
                centAmount
                currencyCode
                fractionDigits
              }
            }
          }
        }
      }
    }
  }
}`