export const PRODUCT_SEARCH_QUERY = `query productSearchQuery($locale:Locale!,$text:String!){
    productProjectionSearch(locale:$locale,text:$text){
      results{
        id
        name(locale:$locale)
        masterVariant{
          sku
          id
          images{
            url
            dimensions{
              height
              width
            }
          }
          price(currency:"USD"){
            id
            value{
              centAmount
              currencyCode
              fractionDigits
            }
          }
        }
        variants{
          sku
          id
          price(currency:"USD"){
            value{
              currencyCode
              centAmount
              fractionDigits
            }
          }
          images{
            url
          }
        }
        slug(locale:$locale)
      }
    }
  }`