"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var graphql_queries_1 = require("./graphql-queries");
Object.defineProperty(exports, "FETCH_TICKETS", { enumerable: true, get: function () { return graphql_queries_1.FETCH_TICKETS; } });
var helper_methods_1 = require("./helper-methods");
Object.defineProperty(exports, "getTicketRows", { enumerable: true, get: function () { return helper_methods_1.getTicketRows; } });
Object.defineProperty(exports, "getTicketCategories", { enumerable: true, get: function () { return helper_methods_1.getTicketCategories; } });
Object.defineProperty(exports, "getTicketPriorityValues", { enumerable: true, get: function () { return helper_methods_1.getTicketPriorityValues; } });
Object.defineProperty(exports, "getTicketContactTypes", { enumerable: true, get: function () { return helper_methods_1.getTicketContactTypes; } });
Object.defineProperty(exports, "getCreateTicketMutaion", { enumerable: true, get: function () { return helper_methods_1.getCreateTicketMutaion; } });
Object.defineProperty(exports, "getCreateTicketDraft", { enumerable: true, get: function () { return helper_methods_1.getCreateTicketDraft; } });
var constants_1 = require("./constants");
Object.defineProperty(exports, "CONSTANTS", { enumerable: true, get: function () { return constants_1.CONSTANTS; } });
