export const FETCH_PAYMENT_BY_ID = `query FetchPaymentById($id:String!){
    payment(id:$id){
       id
          key
          interfaceId
          version
          createdAt
          lastModifiedAt
          paymentStatus{
            interfaceCode
            interfaceText
          }
          custom{
            customFieldsRaw{
              name
              value
            }
          }
          customer{
            id
          }
          amountPlanned{
            type
            currencyCode
            centAmount
            fractionDigits
          }
          paymentMethodInfo{
            paymentInterface
            method
            name(locale:"en")
          }
          transactions{
            id
            interactionId
            timestamp
            type
            state
            amount{
              type
              currencyCode
              fractionDigits
              centAmount
            }
        }
    }
  }`
export const UPDATE_PAYMENT_BY_ID = `mutation updatePayment($id:String!,$version:Long!,$actions:[PaymentUpdateAction!]!){
  updatePayment(id:$id,version:$version,actions:$actions){
    id
  }
}`