# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CSA-Project

on:
  repository_dispatch:
    types: deploy-csa
  push:
    branches: [ "main" ]
    paths:
      - 'rc-csa/**'
      - '.github/workflows/deploy-csa-ci-master.yml'
      - '*.json'
      - '*.yml'
      - '*.yaml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'rc-csa/**'
      - '.github/workflows/deploy-csa-ci-master.yml'
      - '*.json'
      - '*.yml'
      - '*.yaml'    
env:
  FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
  PROJECT_ID: ${{secrets.PROJECT_ID}}
  PROJECT_PATH: rc-csa
  
jobs:
  deploy:
    name: Deploy Firebase function
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [16.x]       
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          cd rc-csa
          npm install --production
          npm run build
          npm run compile-html
          firebase use $PROJECT_ID

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
