name: B2B Order Create API Extension Function CI/CD feature (release/**) flow
on:
  push:
    branches:
      - feature/**
    paths:
      - 'packages/b2b-order-create-api-extension/**'
      - '.github/workflows/order-create-api-extension-ci-feature.yaml'
      - '*.json'
      - '*.yaml'
jobs:
  lint:
    name: Lint (node.js)
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          cd packages/b2b-order-create-api-extension
          npm install --no-audit
      - name: Lint Node.js
        run: |
          cd packages/b2b-order-create-api-extension
          npm run lint
      - name: Lint Markdown
        run: |
          cd packages/b2b-order-create-api-extension
          npm run lint-md    
  test:        
    name: Test
    needs: lint
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          cd packages/b2b-order-create-api-extension
          npm install
          
      - name: Unit Testing
        run: |
          cd packages/b2b-order-create-api-extension
          npm test
